name: corigge
description: A cross-platform Flutter desktop application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.4.10  # For zip file handling
  
  provider: ^6.1.1
  dio: ^5.4.1  # HTTP client for making API requests
  go_router: ^12.1.3
  window_manager: ^0.3.7
  shared_preferences: ^2.2.2
  http: ^1.1.0
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.6
  logging: ^1.3.0
  supabase_flutter: ^2.8.1
  dartz: ^0.10.1
  flutter_svg: ^2.0.9
  google_sign_in_all_platforms: 1.0.0
  google_sign_in: ^6.3.0
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  path: ^1.8.3
  web_socket_channel: ^2.4.0
  encrypt: ^5.0.3
  crypto: ^3.0.3
  another_flushbar: ^1.12.30
  uni_links: ^0.5.1
  flutter_dotenv: ^5.2.1
  dropdown_search: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/
    - assets/images/
    - assets/lib/darwin/
    - assets/lib/linux/
    - assets/lib/windows/
    - .env
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700