site_name: Corigge
site_description: Documentação do projeto Corigge
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
nav:
  - Início: index.md
  - Cenário Atual: cenario-atual.md
  - Documentação do Projeto:
    - Solução Proposta: solucao-proposta.md
    - Estratégias: estrategias.md
    - Engenharia de Requisitos: engenharia-requisitos.md
    - Cronograma: cronograma.md
    - Interação Cliente-Equipe: interacao-cliente.md
    - DoR e DoD: DoR_DoD.md
    - Backlog do Produto: backlog.md
    - Requisitos: requisitos.md
  - Lições Aprendidas: licoes-aprendidas.md
  - Ata de reuniões: gravacoes.md
  - Entregas: entregas.md 

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  
extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

