# mkdocs.yml

site_name: Corigge
site_description: Documentação do projeto Corigge
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
nav:
  - Início: index.md
  - Cenário Atual: cenario-atual.md
  - Documentação do Projeto:
      - Solução Proposta: solucao-proposta.md
      - Estratégias: estrategias.md
      - Engenharia de Requisitos: engenharia-requisitos.md
      - Cronograma: cronograma.md
      - Interação Cliente-Equipe: interacao-cliente.md
      - DoR e DoD: DoR_DoD.md
      - Backlog do Produto: backlog.md
      - Requisitos: requisitos.md
  - Lições Aprendidas: licoes-aprendidas.md
  - Ata de reuniões: gravacoes.md
  - Entregas:
      - Unidade 01: entregas/entrega01.md
      - Unidade 02: entregas/entrega02.md
      - Unidade 03: entregas/entrega03.md
      - PBB: entregas/unidade03/pbb.md
      - USM: entregas/unidade03/usm.md
      - Unidade 04: entregas/entrega04.md
      - UML: entregas/unidade04/uml.md
      - BUILD Aplicativo: corigge.msix
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.tabbed
  - admonition
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - toc: # <-- Adicione esta linha e as seguintes
      permalink: true
      toc_depth: 3 # <-- Isso vai incluir até os cabeçalhos de nível 3 (###) na TOC
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
